version: '3'
services:
  odoo:
    image: odoo:16.0
    env_file: .env
    depends_on:
      - db
    ports:
      - "127.0.0.1:8869:8069"
    volumes:
      - odoo_data:/var/lib/odoo
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

volumes:
  odoo_data:
  db_data:
